/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pizza.gltf 
Author: assetfactory (https://sketchfab.com/assetfactory)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-pizza-restaurant-a1793365c8c145c48128dd75d5a2d2bf
Title: Low poly pizza restaurant
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/pizza.gltf');
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
          <mesh
            geometry={nodes.PizzaBuilding_Texture_buildings1_0.geometry}
            material={materials.Texture_buildings1}
            scale={100}
          />
          <mesh
            geometry={nodes.PizzaTables_Texture_buildings1_0.geometry}
            material={materials.Texture_buildings1}
            scale={100}
          />
          <mesh
            geometry={nodes.PizzaLight_Texture_buildings1_0.geometry}
            material={materials.Texture_buildings1}
            scale={100}
          />
          <mesh
            geometry={nodes.PizzaBoard_Texture_buildings1_0.geometry}
            material={materials.Texture_buildings1}
            scale={100}
          />
          <mesh
            geometry={nodes.Collider_Collider_0.geometry}
            material={materials.Collider}
            rotation={[-Math.PI / 2, 0, 0.012]}
            scale={[54.931, 54.931, 100]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/pizza.gltf');
